import { writeFileSync } from "node:fs";
const base=(process.env.CHATBOT_TEST_URL||"http://localhost:3000").replace(/\/$/,"");
const wp=process.env.SUCCESSIVE_API_BASE_URL.replace(/\/$/,"");
const clean=v=>String(v||"").replace(/<[^>]+>/g," ").replace(/&#0*38;|&amp;/gi,"&").replace(/\s+/g," ").trim();
const types=["page","case_study","industries","partners","post","employee-perspective"];
async function snapshot(){const settled=await Promise.allSettled(types.map(async type=>{const r=await fetch(`${wp}/content?type=${type}&per_page=10&page=1`,{signal:AbortSignal.timeout(20000)});const xs=await r.json();return Array.isArray(xs)?xs:[]}));return settled.flatMap(x=>x.status==="fulfilled"?x.value:[])}
function title(x){return clean(typeof x.title==="string"?x.title:x.title?.rendered)}
function naturalProblem(x,index){const a=x.acf&&typeof x.acf==="object"?x.acf:{};const raw=clean(a.challenge_sub_heading||a.hero_description||a.meta_description||a.summery||a.description||"");const words=raw.split(/\s+/).filter(Boolean);const nouns=words.filter(w=>w.length>5&&!/successive|digital|enterprise|solution|service|client|business/i.test(w)).slice(0,5);const subject=nouns.slice(0,3).join(" ").toLowerCase()||title(x).split(" ").slice(0,3).join(" ").toLowerCase();const patterns=[`Our teams are struggling with ${subject}. Which capability could help us?`,`We need to improve ${subject} without adding more manual work. Where should we start?`,`Our current systems make ${subject} difficult to manage and scale. Can Successive help?`,`We lack reliable visibility into ${subject}. What would you recommend?`,`Too much time is being spent on ${subject}. How could we streamline it?`];return patterns[index%patterns.length]}
const regress=["We need better application performance.","Can you help forestry teams manage field operations?","What is GeoAI and can it support field operations?","Our inventory is inconsistent across marketplace vendors.","Our teams manually reconcile vendor settlements.","Our commerce platform only supports one seller and cannot scale.","We have content spread across six brand websites.","Our application landscape is fragmented across critical systems.","We need faster releases without weakening security.","Our cloud costs keep growing and ownership is unclear."];
const multi=["We need headless CMS capabilities for a travel company. What would you suggest?","Which cloud migration capability fits a healthcare organization with legacy applications?","Do you have a case study about improving application performance in retail?","We use AWS and need to reduce infrastructure costs. Which service fits?","Our agriculture field teams need better location visibility. Can GeoAI help?","We need commerce automation for a multi-vendor marketplace.","Which DevSecOps capability can help a financial services team release safely?","Do you have a whitepaper about modernizing cloud applications?","We need consistent customer experiences across web and mobile in retail.","Our media operations use disconnected planning and reporting systems. What capability fits?"];
const content=["Any case study about cloud migration?","Show me a blog about Kubernetes.","Do you have thought leadership about enterprise architecture?","Is there a webinar specifically about generative AI?","Do you have a whitepaper about application modernization?"];
const scope=["What's tomorrow's weather?","Write a poem about summer.","Recommend a movie.","Who won the football match?","What is the capital of Brazil?"];
async function ask(test,i,history=[]){const s=performance.now();try{const r=await fetch(`${base}/api/chat`,{method:"POST",headers:{"content-type":"application/json","x-forwarded-for":`203.0.113.${i%220+1}`},body:JSON.stringify({message:test.query,history,sessionId:`v4-${i}`}),signal:AbortSignal.timeout(60000)});const p=await r.json();return{...test,success:r.ok&&p.success,status:r.status,durationMs:Math.round(performance.now()-s),answer:p.data?.answer||p.error?.message||"",cards:(p.data?.cards||[]).map(c=>({title:c.title,type:c.type}))}}catch(e){return{...test,success:false,status:0,durationMs:Math.round(performance.now()-s),answer:String(e),cards:[]}}}
const items=await snapshot();const natural=items.filter(x=>{const a=x.acf||{};return clean(a.challenge_sub_heading||a.hero_description||a.meta_description||a.summery||a.description).length>30}).flatMap((x,i)=>[
  {query:naturalProblem(x,i),group:"business",source:title(x)},
  {query:naturalProblem(x,i+2),group:"business",source:title(x)},
]).slice(0,35);
const exact=items.filter(x=>title(x).length>8).slice(0,10).map(x=>({query:`Tell me about ${title(x)}`,group:"exact",expected:title(x)}));
const tests=[...regress.map(query=>({query,group:"regression"})),...natural,...multi.map(query=>({query,group:"multi"})),...content.map(query=>({query,group:"content"})),...exact,...scope.map(query=>({query,group:"scope"}))];
const results=[];for(const [i,t]of tests.entries())results.push(await ask(t,i));
const journeys=[["Tell me about headless CMS.","What about travel companies?","What would you suggest for reducing manual content work?"],["We need better application performance.","What about healthcare?","Show me a relevant case study."],["We need cloud cost control.","Now focus on retail commerce.","How would this help our company?"]];const conversations=[];let ci=300;for(const turns of journeys){const h=[];for(const query of turns){const x=await ask({query,group:"conversation"},ci++,h);conversations.push(x);h.push({role:"user",content:query},{role:"assistant",content:x.answer})}}
const burst=tests.slice(0,8);const concurrency=[];for(const level of[1,2,4]){const xs=[];for(let o=0;o<burst.length;o+=level)xs.push(...await Promise.all(burst.slice(o,o+level).map((t,j)=>ask(t,500+level*20+o+j))));const d=xs.map(x=>x.durationMs).sort((a,b)=>a-b);concurrency.push({level,total:xs.length,successes:xs.filter(x=>x.success).length,timeouts:xs.filter(x=>!x.status).length,p50:d[Math.floor(d.length*.5)],p95:d[Math.min(d.length-1,Math.floor(d.length*.95))]})}
const all=[...results,...conversations],d=all.map(x=>x.durationMs).sort((a,b)=>a-b);const out={snapshot:items.length,tests:results,conversations,concurrency,performance:{total:all.length,successes:all.filter(x=>x.success).length,timeouts:all.filter(x=>!x.status).length,p50:d[Math.floor(d.length*.5)],p95:d[Math.min(d.length-1,Math.floor(d.length*.95))]}};writeFileSync("/tmp/chatbot-v4-results.json",JSON.stringify(out,null,2));console.log(JSON.stringify({counts:Object.fromEntries([...new Set(results.map(x=>x.group))].map(g=>[g,results.filter(x=>x.group===g).length])),conversations:conversations.length,performance:out.performance,concurrency},null,2));
